manifest = "2ef261eb1fe8c4fbaf9f2977ef16bd0c5ad27846cc5ec9e4e430b840f82c7317"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assign"
target = "//:assign"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-conversion"
target = "//:conversion"

[[dependency]]
package = "github.com/buckaroo-pm/boost-fusion"
target = "//:fusion"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-lexical_cast"
target = "//:lexical-cast"

[[dependency]]
package = "github.com/buckaroo-pm/boost-math"
target = "//:math"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-numeric_conversion"
target = "//:numeric-conversion"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[[dependency]]
package = "github.com/buckaroo-pm/boost-proto"
target = "//:proto"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart-ptr"

[lock."github.com/buckaroo-pm/boost-algorithm"]
versions = [ "branch=master" ]
revision = "81660693b6473d0ec6d000a01fd74b7dadd22106"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "branch=master" ]
revision = "6587b84e4fb0711bd7d0930b415ca7937e72021b"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "branch=master" ]
revision = "ea0eab9a8cf538aa81a7d53f1762a5ff7e628e73"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "417f80abf86251b29609a9747dae7756236699aa"

[lock."github.com/buckaroo-pm/boost-assign"]
versions = [ "branch=master" ]
revision = "ad238fac8778c22dc9faf56dc77608c3c25013aa"

[lock."github.com/buckaroo-pm/boost-atomic"]
versions = [ "branch=master" ]
revision = "54e906eaa9d71c68bd0d990727f060e81389f3cb"

[lock."github.com/buckaroo-pm/boost-chrono"]
versions = [ "branch=master" ]
revision = "d9135ae23f09a15931dbd15a99324dfe44954aba"

[lock."github.com/buckaroo-pm/boost-circular_buffer"]
versions = [ "branch=master" ]
revision = "b6d0829b73358fd245368f89c450b18dc182bd94"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "branch=master" ]
revision = "5a8bb5676742a02b9e2d343ecec66639da9deb3e"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "60c77dd14f5bac2b9e6c59f308b7ad20d31f70ab"

[lock."github.com/buckaroo-pm/boost-container"]
versions = [ "branch=master" ]
revision = "ad0d657f10d51aa7a72b6ae530e2e8a13316718e"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "branch=master" ]
revision = "ddd9a887f1f0253ded4455d455b3c54228067b74"

[lock."github.com/buckaroo-pm/boost-conversion"]
versions = [ "branch=master" ]
revision = "e90e9325d05332eea7d87e262eb8deb0174f45ed"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "10b589cb4aea4ca823237059f104cbfdd09b0f0e"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "94aa5268c1a74468be94b40afd730aea1730ceab"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "branch=master" ]
revision = "1795a6e9756f4d9ac60d43e2b9b07ec7ddfdbfb7"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "branch=master" ]
revision = "eed94ad6b518aa07bf79c7cb5ab1af3aa594b7be"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "branch=master" ]
revision = "bb8ffe4d24071f3942a18b274cc7f3ee0dc91eb2"

[lock."github.com/buckaroo-pm/boost-functional"]
versions = [ "branch=master" ]
revision = "28b42e6161041316b359b53682f075522cd48d6f"

[lock."github.com/buckaroo-pm/boost-fusion"]
versions = [ "branch=master" ]
revision = "706a76db5d04f34aeca5a2894ce6060e9044348e"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "branch=master" ]
revision = "5badcf5b232a15e89d0701bef687ffbe70398696"

[lock."github.com/buckaroo-pm/boost-intrusive"]
versions = [ "branch=master" ]
revision = "d812ed3ac7c7d573249e49fe23aa12339629c730"

[lock."github.com/buckaroo-pm/boost-io"]
versions = [ "branch=master" ]
revision = "70c28ebaa83b1fd6907db8f542d7be8abc6835b4"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "branch=master" ]
revision = "c84fc34d0f6386edb15b0cb854a12864b6f15232"

[lock."github.com/buckaroo-pm/boost-lexical_cast"]
versions = [ "branch=master" ]
revision = "9f6d656caf4b0037327c426219de6ef676a2ccdc"

[lock."github.com/buckaroo-pm/boost-math"]
versions = [ "branch=master" ]
revision = "e5e11d021064a102a7f1258c8c52fcb40ca25be9"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "branch=master" ]
revision = "3f0711cabd643ed902ff3ae3d6746ba2f7256e4e"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "branch=master" ]
revision = "6493fcda0f5cd2ee595346ca48ff495db9fa74d5"

[lock."github.com/buckaroo-pm/boost-multiprecision"]
versions = [ "branch=master" ]
revision = "466fe3d1bec248781b4b26d98ee6cf0f57d92017"

[lock."github.com/buckaroo-pm/boost-numeric_conversion"]
versions = [ "branch=master" ]
revision = "35fa920e0b53c124b0b5972b1802032933c71fca"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "branch=master" ]
revision = "9c3529ad17d35171ffaa689ebfee9f21ce616129"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "branch=master" ]
revision = "73def0812b7235e0312079c729342787819bf1d5"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "a70772bbd315eb597c3f1e359af742dde46a6f37"

[lock."github.com/buckaroo-pm/boost-proto"]
versions = [ "branch=master" ]
revision = "153d707e0fbf7ea9898d5566e56264f0b181e320"

[lock."github.com/buckaroo-pm/boost-ptr_container"]
versions = [ "branch=master" ]
revision = "66db4689881b75f9acf3a83c42d6e144480fe60d"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "branch=master" ]
revision = "10482c9459133c139137e459d8e1051246866983"

[lock."github.com/buckaroo-pm/boost-ratio"]
versions = [ "branch=master" ]
revision = "1b80056654a5ca6384e54d925cfdd58feee28f63"

[lock."github.com/buckaroo-pm/boost-rational"]
versions = [ "branch=master" ]
revision = "7a75e06a78e0481cb636412a62764f628ec8e56b"

[lock."github.com/buckaroo-pm/boost-regex"]
versions = [ "branch=master" ]
revision = "c03a752db0bc55e196e4866e7d8fb9792bfbe4a5"

[lock."github.com/buckaroo-pm/boost-serialization"]
versions = [ "branch=master" ]
revision = "3cb7f143fead7a6a21f99d58bc2154bb6f85a031"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "branch=master" ]
revision = "613f7a038214f92d7235de669bedc3710657f353"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "branch=master" ]
revision = "4b9da4628bc69ad0e9b244d3ec885f2eadac95d8"

[lock."github.com/buckaroo-pm/boost-system"]
versions = [ "branch=master" ]
revision = "d98315738ee47380f52e43d790d1c42cf549b175"

[lock."github.com/buckaroo-pm/boost-test"]
versions = [ "branch=master" ]
revision = "205019c90a5e5e839fecabe65c3424f3a5887c49"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "branch=master" ]
revision = "788503e2365554d1860c6d2043999e3430d1f7a5"

[lock."github.com/buckaroo-pm/boost-timer"]
versions = [ "branch=master" ]
revision = "78b132cf3377047d805c1ebbd90b11a0d2b9bdae"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "branch=master" ]
revision = "5ffb0abec6da0d9986690b32d20218769a50086b"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "branch=master" ]
revision = "a8183e0bdcaafdda1183c0279137acadcb5b4466"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "a34caf51f831ffb77d1057c668b5db620863d191"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "branch=master" ]
revision = "e8cb7bc76c55f02a24f824fecf5cdf0629dc3aa4"

[lock."github.com/buckaroo-pm/boost-ublas"]
versions = [ "branch=master" ]
revision = "1cf282fd9cca5c81388251c25c65adc0d3f8cfb3"

[lock."github.com/buckaroo-pm/boost-unordered"]
versions = [ "branch=master" ]
revision = "7fe9837e937e161a537fcb869a678bfe54d18b2c"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "branch=master" ]
revision = "57aa216434800315c9cd2664169e444e3070a677"

[lock."github.com/buckaroo-pm/boost-winapi"]
versions = [ "branch=master" ]
revision = "92c47b2e1db8a7c023d394e979f81438b410fd18"

[lock."github.com/buckaroo-pm/icu4c"]
versions = [ "branch=master" ]
revision = "d6803681f02ef9395665d4db6e84a4416a679bc3"
